server.port=8083

#community.service.url=http://localhost:8084
community.service.url=http://localhost:57338
community.service.addCommunity.path=/api/community
group.service.addGroup.path=/api/groups
group.service.getGroups.path=/api/groups/community

user.post.service.url=http://localhost:8081
user.post.service.addPost.path=/api/post
user.post.service.updatePost.path=/api/post
user.post.service.getPostsByCommunityId.path=/api/post/community/
user.post.service.getPostsByGroupId.path=/api/post/group/

user.comment.service.url=http://localhost:8082
user.comment.service.addComment.path=/api/comments
user.comment.service.updateComment.path=/api/comments
user.comment.service.getCommentsByPostId.path=/api/comments/post/
spring.application.name=Community Orchestration Service
management.tracing.sampling.probability=1.0
springdoc.api-docs.path=/community-orchestration-api-docs